# Generated by Django 5.2.6 on 2025-09-16 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printjob',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='printjob',
            name='copies',
        ),
        migrations.RemoveField(
            model_name='printjob',
            name='paper_size',
        ),
        migrations.AlterField(
            model_name='printjob',
            name='barcode_mapping',
            field=models.ForeignKey(help_text='The barcode mapping that was viewed/printed', on_delete=django.db.models.deletion.CASCADE, to='app.barcodepagemapping'),
        ),
        migrations.AlterField(
            model_name='printjob',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error message if any issue occurred'),
        ),
        migrations.AlterField(
            model_name='printjob',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=20),
        ),
    ]
