# Generated by Django 5.2.6 on 2025-10-29 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_printjob_completed_at_remove_printjob_copies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printjob',
            name='barcode_mapping',
            field=models.ForeignKey(help_text='The barcode mapping that was viewed/printed', on_delete=django.db.models.deletion.CASCADE, related_name='print_jobs', to='app.barcodepagemapping'),
        ),
    ]
